USE PMS_DB;

-- companies
INSERT INTO companies VALUES (1, 'Aerials', 'Erevan');
INSERT INTO companies VALUES (2, 'MicroSys', 'New-York');
INSERT INTO companies VALUES (3, 'CodeWarriors', 'Taibay');
INSERT INTO companies VALUES (4, '10000000Geeeks', 'London');
INSERT INTO companies VALUES (5, 'Cinnamon', 'Madrid');
INSERT INTO companies VALUES (6, 'Back&', 'Kyiv');

-- customers
INSERT INTO customers VALUES (1, 'IBM', 'Armonk', 'Engineering');
INSERT INTO customers VALUES (2, 'Apple Inc.', 'Paolo Alto', 'Electronics');
INSERT INTO customers VALUES (3, 'FOXCONN', 'Taibay', 'Manufacturing');
INSERT INTO customers VALUES (4, 'Ministry of Defence', 'Washington', 'Military');
INSERT INTO customers VALUES (5, 'FIFA', 'Zurich', 'Sports');
INSERT INTO customers VALUES (6, 'BionicTech', 'Chicago', 'Medicine');
INSERT INTO customers VALUES (7, 'Electronic Arts', 'Redwood', 'Entertainment');
INSERT INTO customers VALUES (8, 'Ministry of Education', 'Washington', 'Education');

-- projects
INSERT INTO projects VALUES (1, 'Kids Educational App', 'Mobile', 4, 8);
INSERT INTO projects VALUES (2, 'Legends of Zelda XXI', 'Gaming', 3, 7);
INSERT INTO projects VALUES (3, 'Combat Management System', 'Military', 6, 4);
INSERT INTO projects VALUES (4, 'Orbital Monitoring System','Military/Science', 5, 4);
INSERT INTO projects VALUES (5, 'AI Referee', 'Sports', 2, 5);
INSERT INTO projects VALUES (6, 'Conduit software', 'Medicine', 2, 6);
INSERT INTO projects VALUES (7, 'Robots software', 'Engineering', 1, 3);
INSERT INTO projects VALUES (8, 'Operational System', 'Computers', 4, 2);
INSERT INTO projects VALUES (9, 'Hardware controllers', 'Computers', 5, 2);
INSERT INTO projects VALUES (10, 'Manufacturing lines QA', 'Engineering', 1, 1);
INSERT INTO projects VALUES (11, 'Students application', 'Educational/Internet', 6, 8);

-- developers
INSERT INTO developers VALUES (1, 'John', 'Doe', 32, 'M', 1);
INSERT INTO developers VALUES (2, 'Sarah', 'Connor', 44, 'F', 1);
INSERT INTO developers VALUES (3, 'Thomas', 'Anderson', 26, 'M', 1);
INSERT INTO developers VALUES (4, 'Minny', 'Mouse', 28, 'F', 1);
INSERT INTO developers VALUES (5, 'Penny', 'Wise', 18, 'M', 2);
INSERT INTO developers VALUES (6, 'Donna', 'Corleone', 23, 'F', 2);
INSERT INTO developers VALUES (7, 'Tanny', 'Manner', 32, 'M', 2);
INSERT INTO developers VALUES (8, 'Johanna', 'Perrone', 45, 'F', 2);
INSERT INTO developers VALUES (9, 'Tommy', 'Gunn', 33, 'M', 3);
INSERT INTO developers VALUES (10, 'Samantha', 'Smith', 22, 'F', 3);
INSERT INTO developers VALUES (11, 'Paul', 'Athredis', 28, 'M', 3);
INSERT INTO developers VALUES (12, 'Jessica', 'Athredis', 32, 'F', 3);
INSERT INTO developers VALUES (13, 'Sam', 'Wise', 46, 'M', 4);
INSERT INTO developers VALUES (14, 'Angva', 'Uberwald', 25, 'F', 4);
INSERT INTO developers VALUES (15, 'Fred', 'Colone', 52, 'M', 4);
INSERT INTO developers VALUES (16, 'Sibilla', 'Ownec', 44, 'F', 4);
INSERT INTO developers VALUES (17, 'Havelock', 'Vitinary', 32, 'M', 5);
INSERT INTO developers VALUES (18, 'Rosy', 'Whitemane', 23, 'F', 5);
INSERT INTO developers VALUES (19, 'Knocky', 'Knock', 52, 'M', 5);
INSERT INTO developers VALUES (20, 'Bella', 'Araho', 31, 'F', 5);
INSERT INTO developers VALUES (21, 'Maxym', 'Denysiuk', 23, 'M', 6);
INSERT INTO developers VALUES (22, 'Anastasiia', 'Otroshenko', 32, 'F', 6);
INSERT INTO developers VALUES (23, 'Pavlo', 'Karakata', 36, 'M', 6);
INSERT INTO developers VALUES (24, 'Mariya', 'Bielova', 23, 'F', 6);

-- skills
INSERT INTO skills VALUES (1, 'C++', 'Trainee');
INSERT INTO skills VALUES (2, 'C++', 'Junior');
INSERT INTO skills VALUES (3, 'C++', 'Middle');
INSERT INTO skills VALUES (4, 'C++', 'Senior');
INSERT INTO skills VALUES (5, 'Python', 'Trainee');
INSERT INTO skills VALUES (6, 'Python', 'Junior');
INSERT INTO skills VALUES (7, 'Python', 'Middle');
INSERT INTO skills VALUES (8, 'Python', 'Senior');
INSERT INTO skills VALUES (9, 'Java', 'Trainee');
INSERT INTO skills VALUES (10, 'Java', 'Junior');
INSERT INTO skills VALUES (11, 'Java', 'Middle');
INSERT INTO skills VALUES (12, 'Java', 'Senior');
INSERT INTO skills VALUES (13, 'Ruby', 'Trainee');
INSERT INTO skills VALUES (14, 'Ruby', 'Junior');
INSERT INTO skills VALUES (15, 'Ruby', 'Middle');
INSERT INTO skills VALUES (16, 'Ruby', 'Senior');
INSERT INTO skills VALUES (17, 'JS', 'Trainee');
INSERT INTO skills VALUES (18, 'JS', 'Junior');
INSERT INTO skills VALUES (19, 'JS', 'Middle');
INSERT INTO skills VALUES (20, 'JS', 'Senior');
INSERT INTO skills VALUES (21, '.NET', 'Trainee');
INSERT INTO skills VALUES (22, '.NET', 'Junior');
INSERT INTO skills VALUES (23, '.NET', 'Middle');
INSERT INTO skills VALUES (24, '.NET', 'Senior');
INSERT INTO skills VALUES (25, 'C#', 'Trainee');
INSERT INTO skills VALUES (26, 'C#', 'Junior');
INSERT INTO skills VALUES (27, 'C#', 'Middle');
INSERT INTO skills VALUES (28, 'C#', 'Senior');

-- developer_skills
INSERT INTO developers_skills VALUES (1, 3);
INSERT INTO developers_skills VALUES (1, 7);
INSERT INTO developers_skills VALUES (2, 11);
INSERT INTO developers_skills VALUES (2, 20);
INSERT INTO developers_skills VALUES (2, 27);
INSERT INTO developers_skills VALUES (3, 4);
INSERT INTO developers_skills VALUES (3, 11);
INSERT INTO developers_skills VALUES (4, 1);
INSERT INTO developers_skills VALUES (4, 7);
INSERT INTO developers_skills VALUES (5, 5);
INSERT INTO developers_skills VALUES (5, 25);
INSERT INTO developers_skills VALUES (6, 15);
INSERT INTO developers_skills VALUES (6, 19);
INSERT INTO developers_skills VALUES (6, 26);
INSERT INTO developers_skills VALUES (7, 8);
INSERT INTO developers_skills VALUES (7, 1);
INSERT INTO developers_skills VALUES (8, 15);
INSERT INTO developers_skills VALUES (8, 25);
INSERT INTO developers_skills VALUES (9, 4);
INSERT INTO developers_skills VALUES (10, 11);
INSERT INTO developers_skills VALUES (10, 16);
INSERT INTO developers_skills VALUES (11, 3);
INSERT INTO developers_skills VALUES (12, 28);
INSERT INTO developers_skills VALUES (13, 6);
INSERT INTO developers_skills VALUES (13, 13);
INSERT INTO developers_skills VALUES (14, 3);
INSERT INTO developers_skills VALUES (15, 26);
INSERT INTO developers_skills VALUES (15, 8);
INSERT INTO developers_skills VALUES (16, 1);
INSERT INTO developers_skills VALUES (17, 8);
INSERT INTO developers_skills VALUES (18, 23);
INSERT INTO developers_skills VALUES (18, 11);
INSERT INTO developers_skills VALUES (19, 18);
INSERT INTO developers_skills VALUES (20, 14);
INSERT INTO developers_skills VALUES (20, 22);
INSERT INTO developers_skills VALUES (21, 4);
INSERT INTO developers_skills VALUES (22, 16);
INSERT INTO developers_skills VALUES (23, 6);
INSERT INTO developers_skills VALUES (23, 10);
INSERT INTO developers_skills VALUES (24, 25);
INSERT INTO developers_skills VALUES (24, 11);

-- developer_projects
INSERT INTO developers_projects VALUES (1, 7);
INSERT INTO developers_projects VALUES (2, 10);
INSERT INTO developers_projects VALUES (3, 10);
INSERT INTO developers_projects VALUES (4, 10);
INSERT INTO developers_projects VALUES (5, 5);
INSERT INTO developers_projects VALUES (6, 5);
INSERT INTO developers_projects VALUES (7, 6);
INSERT INTO developers_projects VALUES (8, 6);
INSERT INTO developers_projects VALUES (9, 2);
INSERT INTO developers_projects VALUES (10, 2);
INSERT INTO developers_projects VALUES (11, 2);
INSERT INTO developers_projects VALUES (12, 2);
INSERT INTO developers_projects VALUES (13, 1);
INSERT INTO developers_projects VALUES (14, 1);
INSERT INTO developers_projects VALUES (15, 1);
INSERT INTO developers_projects VALUES (16, 8);
INSERT INTO developers_projects VALUES (17, 9);
INSERT INTO developers_projects VALUES (18, 9);
INSERT INTO developers_projects VALUES (19, 4);
INSERT INTO developers_projects VALUES (20, 4);
INSERT INTO developers_projects VALUES (21, 3);
INSERT INTO developers_projects VALUES (22, 3);
INSERT INTO developers_projects VALUES (23, 3);
INSERT INTO developers_projects VALUES (24, 11);

-- add salaries
ALTER TABLE developers ADD COLUMN salary INT;
UPDATE developers SET salary = 2500 WHERE (id = 1);
UPDATE developers SET salary = 3200 WHERE (id = 2);
UPDATE developers SET salary = 1800 WHERE (id = 3);
UPDATE developers SET salary = 6400 WHERE (id = 4);
UPDATE developers SET salary = 5500 WHERE (id = 5);
UPDATE developers SET salary = 2182 WHERE (id = 6);
UPDATE developers SET salary = 4568 WHERE (id = 7);
UPDATE developers SET salary = 3200 WHERE (id = 8);
UPDATE developers SET salary = 6600 WHERE (id = 9);
UPDATE developers SET salary = 2500 WHERE (id = 10);
UPDATE developers SET salary = 1700 WHERE (id = 11);
UPDATE developers SET salary = 1950 WHERE (id = 12);
UPDATE developers SET salary = 2200 WHERE (id = 13);
UPDATE developers SET salary = 2500 WHERE (id = 14);
UPDATE developers SET salary = 5600 WHERE (id = 15);
UPDATE developers SET salary = 4120 WHERE (id = 16);
UPDATE developers SET salary = 3560 WHERE (id = 17);
UPDATE developers SET salary = 3800 WHERE (id = 18);
UPDATE developers SET salary = 4100 WHERE (id = 19);
UPDATE developers SET salary = 5200 WHERE (id = 20);
UPDATE developers SET salary = 6500 WHERE (id = 21);
UPDATE developers SET salary = 3150 WHERE (id = 22);
UPDATE developers SET salary = 2200 WHERE (id = 23);
UPDATE developers SET salary = 1200 WHERE (id = 24);

-- add project cost and start date
ALTER TABLE projects ADD COLUMN cost DOUBLE;
UPDATE projects SET cost = 100500 WHERE (id = 1);
UPDATE projects SET cost = 225000 WHERE (id = 2);
UPDATE projects SET cost = 850000 WHERE (id = 3);
UPDATE projects SET cost = 430000 WHERE (id = 4);
UPDATE projects SET cost = 560500 WHERE (id = 5);
UPDATE projects SET cost = 1250000 WHERE (id = 6);
UPDATE projects SET cost = 345000 WHERE (id = 7);
UPDATE projects SET cost = 440000 WHERE (id = 8);
UPDATE projects SET cost = 2250000 WHERE (id = 9);
UPDATE projects SET cost = 235000 WHERE (id = 10);
UPDATE projects SET cost = 755000 WHERE (id = 11);
ALTER TABLE projects ADD COLUMN start_date DATE;
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 1);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 2);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 3);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 4);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 5);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 6);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 7);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 8);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 9);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 10);
UPDATE projects SET start_date = CURRENT_DATE() WHERE (id = 11);